version: '3'
services:
  mongo:
    image: "mongo:3.4"
    container_name: 
      mongo
    ports:
      - "27017:27017"
    volumes: 
      - ./configdb:/data/configdb
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: fangwei0505
    command: mongod --auth
